Repository EFUB5-copybara/Backend, pull requests merged in 2025-07, with the labels that each got.

#8 chore: CORS 정책 설정 추가
  src/main/java/efub/cpbr/crumble/global/config/CorsConfig.java
  src/main/resources/application.yml
Labels: chore

#10 [FEAT] Swagger 버전 수정 및 question 날짜별 조회 API 구현
  build.gradle
  src/main/java/efub/cpbr/crumble/global/exception/ErrorCode.java
  src/main/java/efub/cpbr/crumble/question/controller/QuestionController.java
  src/main/java/efub/cpbr/crumble/question/dto/res/QuestionResponse.java
  src/main/java/efub/cpbr/crumble/question/entity/Question.java
  src/main/java/efub/cpbr/crumble/question/repository/QuestionRepository.java
  src/main/java/efub/cpbr/crumble/question/service/QuestionService.java
Labels: feat

#15 [FEAT] 캘린더 api 구현
  src/main/java/efub/cpbr/crumble/calendar/controller/CalendarController.java
  src/main/java/efub/cpbr/crumble/calendar/dto/AnswerDto.java
  src/main/java/efub/cpbr/crumble/calendar/dto/AnsweredDatesResponse.java
  src/main/java/efub/cpbr/crumble/calendar/repository/CalendarRepository.java
  src/main/java/efub/cpbr/crumble/calendar/service/CalendarService.java
Labels: feat

#29 [HOTFIX] findQuestionByDateOrThrow 메서드명 변경 누락된 호출부 수정
  src/main/java/efub/cpbr/crumble/answer/service/AnswerService.java
Labels: hotfix

#31 [FEAT] login 인증 로직, RedisConfig 및 인증 주입 활성화
  src/main/java/efub/cpbr/crumble/answer/controller/AnswerController.java
  src/main/java/efub/cpbr/crumble/auth/controller/AuthController.java
  src/main/java/efub/cpbr/crumble/auth/service/AuthService.java
  src/main/java/efub/cpbr/crumble/calendar/controller/CalendarController.java
  src/main/java/efub/cpbr/crumble/global/config/RedisConfig.java
  src/main/java/efub/cpbr/crumble/global/config/WebSecurityConfig.java
  src/main/java/efub/cpbr/crumble/item/controller/FortuneController.java
  src/main/java/efub/cpbr/crumble/item/controller/UserItemController.java
  src/main/java/efub/cpbr/crumble/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: feat
